# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-08 11:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cancha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('telefono', models.IntegerField()),
                ('direccion', models.CharField(max_length=500)),
                ('tipodecancha', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('telefono', models.IntegerField()),
                ('email', models.CharField(max_length=200)),
                ('edad', models.IntegerField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.IntegerField()),
                ('cancha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partidoya.Cancha')),
                ('jugadores', models.ManyToManyField(to='partidoya.Jugador')),
            ],
        ),
    ]
