# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-10 13:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('partidoya', '0004_cancha_precios'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jugador',
            name='email',
        ),
        migrations.RemoveField(
            model_name='jugador',
            name='nombre',
        ),
        migrations.AddField(
            model_name='cancha',
            name='usuario',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
