# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-01 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partidoya', '0005_auto_20171110_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancha',
            name='imagen',
            field=models.ImageField(default='null', upload_to='static/img'),
        ),
    ]
